/**
 * Pixel art for the hero scene, authored as character grids.
 *
 * Monochrome ramp, darkest to lightest:
 *   k  ink outline      d  dark (hair, trousers, shadow)
 *   m  mid (shirt)      l  light (skin, wall)
 *   w  near white (glass, highlight)      .  transparent
 *
 * Every frame in a set shares the same dimensions so a sprite never jumps
 * between frames. `bun run art:check` (scripts/check-pixel-art.mjs) asserts it.
 */

export type PixelFrame = readonly string[]

export const PIXEL_PALETTE = {
  k: 'var(--px-ink)',
  d: 'var(--px-dark)',
  m: 'var(--px-mid)',
  l: 'var(--px-light)',
  w: 'var(--px-white)',
} as const

/* ---------------------------------------------------------------- character */
/* 16 wide, 24 tall. Anchored so the feet sit on the last row. */

export const CHARACTER_IDLE: PixelFrame = [
  '................',
  '................',
  '.....kkkkkk.....',
  '....kkkkkkkk....',
  '....kkddddkk....',
  '....kllllllk....',
  '....klkllklk....',
  '....kllllllk....',
  '....kllddllk....',
  '....kllllllk....',
  '.....kllllk.....',
  '......kllk......',
  '..kdkddddddkdk..',
  '..kdkddddddkdk..',
  '..klkddddddklk..',
  '..klkddddddklk..',
  '..klkddddddklk..',
  '....kddddddk....',
  '....kkkkkkkk....',
  '....kdk..kdk....',
  '....kdk..kdk....',
  '....kdk..kdk....',
  '....kdk..kdk....',
  '...kkkk..kkkk...',
]

/** Idle with the eyes dropped a row, which reads as a blink. */
export const CHARACTER_BLINK: PixelFrame = [
  '................',
  '................',
  '.....kkkkkk.....',
  '....kkkkkkkk....',
  '....kkddddkk....',
  '....kllllllk....',
  '....kllllllk....',
  '....klkllklk....',
  '....kllddllk....',
  '....kllllllk....',
  '.....kllllk.....',
  '......kllk......',
  '..kdkddddddkdk..',
  '..kdkddddddkdk..',
  '..klkddddddklk..',
  '..klkddddddklk..',
  '..klkddddddklk..',
  '....kddddddk....',
  '....kkkkkkkk....',
  '....kdk..kdk....',
  '....kdk..kdk....',
  '....kdk..kdk....',
  '....kdk..kdk....',
  '...kkkk..kkkk...',
]

/** Contact pose: one leg forward, one trailing, body at full height. */
export const CHARACTER_WALK_A: PixelFrame = [
  '................',
  '................',
  '.....kkkkkk.....',
  '....kkkkkkkk....',
  '....kkddddkk....',
  '....kllllllk....',
  '....klkllklk....',
  '....kllllllk....',
  '....kllddllk....',
  '....kllllllk....',
  '.....kllllk.....',
  '......kllk......',
  '..kdkddddddkdk..',
  '..kdkddddddkdk..',
  '..klkddddddklk..',
  '..klkddddddklk..',
  '..klkddddddklk..',
  '....kddddddk....',
  '....kkkkkkkk....',
  '....kdk..kdk....',
  '....kdk..kdk....',
  '...kdk....kdk...',
  '...kdk....kdk...',
  '..kkkk....kkkk..',
]

/** Passing pose: legs together, whole body a pixel lower for the walk bob. */
export const CHARACTER_WALK_B: PixelFrame = [
  '................',
  '................',
  '................',
  '.....kkkkkk.....',
  '....kkkkkkkk....',
  '....kkddddkk....',
  '....kllllllk....',
  '....klkllklk....',
  '....kllllllk....',
  '....kllddllk....',
  '....kllllllk....',
  '.....kllllk.....',
  '......kllk......',
  '..kdkddddddkdk..',
  '..kdkddddddkdk..',
  '..klkddddddklk..',
  '..klkddddddklk..',
  '....kddddddk....',
  '....kkkkkkkk....',
  '.....kdkkdk.....',
  '.....kdkkdk.....',
  '.....kdkkdk.....',
  '.....kdkkdk.....',
  '....kkkkkkkk....',
]

/** Near arm raised, hand open above the head. */
export const CHARACTER_WAVE_UP: PixelFrame = [
  '................',
  '................',
  '.....kkkkkk.ll..',
  '....kkkkkkkkll..',
  '....kkddddkkkl..',
  '....kllllllkkl..',
  '....klkllklkkl..',
  '....kllllllkkl..',
  '....kllddllkkl..',
  '....kllllllkkl..',
  '.....kllllk.kl..',
  '......kllk..kl..',
  '..kdkddddddkkd..',
  '..kdkddddddkkd..',
  '..klkddddddk....',
  '..klkddddddk....',
  '..klkddddddk....',
  '....kddddddk....',
  '....kkkkkkkk....',
  '....kdk..kdk....',
  '....kdk..kdk....',
  '....kdk..kdk....',
  '....kdk..kdk....',
  '...kkkk..kkkk...',
]

/** Second wave frame: the hand tips outward. */
export const CHARACTER_WAVE_OUT: PixelFrame = [
  '................',
  '................',
  '.....kkkkkk..ll.',
  '....kkkkkkkk.ll.',
  '....kkddddkkkl..',
  '....kllllllkkl..',
  '....klkllklkkl..',
  '....kllllllkkl..',
  '....kllddllkkl..',
  '....kllllllkkl..',
  '.....kllllk.kl..',
  '......kllk..kl..',
  '..kdkddddddkkd..',
  '..kdkddddddkkd..',
  '..klkddddddk....',
  '..klkddddddk....',
  '..klkddddddk....',
  '....kddddddk....',
  '....kkkkkkkk....',
  '....kdk..kdk....',
  '....kdk..kdk....',
  '....kdk..kdk....',
  '....kdk..kdk....',
  '...kkkk..kkkk...',
]

/** Both arms straight up. */
export const CHARACTER_STRETCH: PixelFrame = [
  '................',
  '................',
  '..ll.kkkkkk.ll..',
  '..llkkkkkkkkll..',
  '..klkkddddkkkl..',
  '..klkllllllkkl..',
  '..klklkllklkkl..',
  '..klkllllllkkl..',
  '..klkllddllkkl..',
  '..klkllllllkkl..',
  '..kl.kllllk.kl..',
  '..kl..kllk..kl..',
  '..kdkddddddkkd..',
  '..kdkddddddkkd..',
  '....kddddddk....',
  '....kddddddk....',
  '....kddddddk....',
  '....kddddddk....',
  '....kkkkkkkk....',
  '....kdk..kdk....',
  '....kdk..kdk....',
  '....kdk..kdk....',
  '....kdk..kdk....',
  '...kkkk..kkkk...',
]

/** Sitting with the knees drawn up. */
export const CHARACTER_SIT: PixelFrame = [
  '................',
  '................',
  '................',
  '................',
  '.....kkkkkk.....',
  '....kkkkkkkk....',
  '....kkddddkk....',
  '....kllllllk....',
  '....klkllklk....',
  '....kllllllk....',
  '....kllddllk....',
  '....kllllllk....',
  '.....kllllk.....',
  '......kllk......',
  '....kddddddk....',
  '..kdkddddddkdk..',
  '..kdkddddddkdk..',
  '..klkddddddklk..',
  '....kkkkkkkk....',
  '...kddddddddk...',
  '...kdkkkkkkdk...',
  '...kdk....kdk...',
  '...kdk....kdk...',
  '..kkkk....kkkk..',
]

/* -------------------------------------------------------------------- house */
/* 28 wide, 30 tall. */

export const HOUSE_CLOSED: PixelFrame = [
  '....................kkkk....',
  '....................kddk....',
  '....................kddk....',
  '............kkkk....kddk....',
  '...........kkddkk...kddk....',
  '..........kkddddkk..kddk....',
  '.........kkddddddkkkkddk....',
  '........kkddddddddkkddddk...',
  '.......kkddddddddddddddddk..',
  '......kkddddddddddddddddddk.',
  '.....kkddddddddddddddddddddk',
  '....kkkkkkkkkkkkkkkkkkkkkkkk',
  '......kkkkkkkkkkkkkkkkkkkk..',
  '......kllllllllllllllllllk..',
  '......kllllllllllllllllllk..',
  '......klkkkkkkkkkllllllllk..',
  '......klkwwwkwwwkllllllllk..',
  '......klkwwwkwwwkllllllllk..',
  '......klkkkkkkkkkllllllllk..',
  '......klkwwwkwwwkllllllllk..',
  '......klkwwwkwwwkllllllllk..',
  '......klkwwwkwwwklkkkkkkkk..',
  '......klkkkkkkkkklkdddddkk..',
  '......klllllllllllkdddddkk..',
  '......klllllllllllkdddddkk..',
  '......klllllllllllklddddkk..',
  '......klllllllllllkdddddkk..',
  '......klllllllllllkdddddkk..',
  '......klllllllllllkdddddkk..',
  '......kkkkkkkkkkkkkkkkkkkk..',
]

export const HOUSE_OPEN: PixelFrame = [
  '....................kkkk....',
  '....................kddk....',
  '....................kddk....',
  '............kkkk....kddk....',
  '...........kkddkk...kddk....',
  '..........kkddddkk..kddk....',
  '.........kkddddddkkkkddk....',
  '........kkddddddddkkddddk...',
  '.......kkddddddddddddddddk..',
  '......kkddddddddddddddddddk.',
  '.....kkddddddddddddddddddddk',
  '....kkkkkkkkkkkkkkkkkkkkkkkk',
  '......kkkkkkkkkkkkkkkkkkkk..',
  '......kllllllllllllllllllk..',
  '......kllllllllllllllllllk..',
  '......klkkkkkkkkkllllllllk..',
  '......klkwwwkwwwkllllllllk..',
  '......klkwwwkwwwkllllllllk..',
  '......klkkkkkkkkkllllllllk..',
  '......klkwwwkwwwkllllllllk..',
  '......klkwwwkwwwkllllllllk..',
  '......klkwwwkwwwklkkkkkkkk..',
  '......klkkkkkkkkklkkkkkkkk..',
  '......klllllllllllkkkkkkkk..',
  '......klllllllllllkkkkkkkk..',
  '......klllllllllllkkkkkkkk..',
  '......klllllllllllkkkkkkkk..',
  '......klllllllllllkkkkkkkk..',
  '......klllllllllllkkkkkkkk..',
  '......kkkkkkkkkkkkkkkkkkkk..',
]

/* -------------------------------------------------------------------- props */

/** 14 wide, 24 tall. Something to walk over to. */
export const TREE: PixelFrame = [
  '.....kkk......',
  '...kkdddkk....',
  '..kddddddddk..',
  '.kdddmmmmdddk.',
  'kddmmmmmmmmddk',
  'kdmmmmmmmmmmdk',
  'kdmmmmmmmmmmdk',
  'kdmmmmmmmmmmdk',
  'kddmmmmmmmmddk',
  '.kddmmmmmmddk.',
  '..kddmmmmddk..',
  '...kkddddkk...',
  '....kkddkk....',
  '.....kkkk.....',
  '.....kddk.....',
  '.....kddk.....',
  '.....kddk.....',
  '.....kddk.....',
  '.....kddk.....',
  '.....kddk.....',
  '.....kddk.....',
  '....kddddk....',
  '...kddddddk...',
  '..kkkkkkkkkk..',
]

/** 6 wide, 6 tall. Rises from the chimney while someone is home. */
export const SMOKE: PixelFrame = [
  '..ll..',
  '.lmml.',
  'lmmmml',
  'lmmmml',
  '.lmml.',
  '..ll..',
]
